# Generated by Django 3.1.6 on 2021-02-01 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210201_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BinaryField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
